### ISSUE TITLE
Impossible to obtain the same results with the pretrained model

### ISSUE THREAD

**Issue by Malrick** [JizhiziLi/AIM#10]
Hello, 

Thanks for the great work, I believe your research is really interesting!

I'd like to report issues obtaining the results displayed on the README. 

FIrst, when running on the same environment as described on the README (with torch=1.4.0), I run in the following exception:

```
Traceback (most recent call last):
  File "core/test.py", line 321, in <module>
    load_model_and_deploy(args)
  File "core/test.py", line 298, in load_model_and_deploy
    ckpt = torch.load(args.model_path,map_location=torch.device('cpu'))
  File "/home/malrick/anaconda3/envs/aim-env/lib/python3.6/site-packages/torch/serialization.py", line 527, in load
    with _open_zipfile_reader(f) as opened_zipfile:
  File "/home/malrick/anaconda3/envs/aim-env/lib/python3.6/site-packages/torch/serialization.py", line 224, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: version_ <= kMaxSupportedFileFormatVersion INTERNAL ASSERT FAILED at /opt/conda/conda-bld/pytorch_1579022034529/work/caffe2/serialize/inline_container.cc:132, please report a bug to PyTorch. Attempted to read a PyTorch file with version 3, but the maximum supported version for reading is 2. Your PyTorch installation may be too old. (init at /opt/conda/conda-bld/pytorch_1579022034529/work/caffe2/serialize/inline_container.cc:132)
```

So it seems that the pre-trained model can't be read with such an old version of PyTorch. The export of the conda environment is available here: [aim-env.txt](https://github.com/JizhiziLi/AIM/files/7354296/aim-env.txt) (just replace .txt extension with .yml, GitHub doesn't support hosting yml files)

---------

I then ran the script with the same environment that @JizhiziLi described in #7 (PyTorch 1.7.1, and python 3.7.7). 
Conda export is available here: [aim-env-2.txt](https://github.com/JizhiziLi/AIM/files/7354411/aim-env-2.txt)

I have set the parameter `test_choice=Hybrid`, in file `core/scripts/test_samples.sh`, and I have the ratios set to `global_ratio=1/4, local_ratio=1/2` in file `core/test.py`

Also, as my RTX3090 is not supported by these older versions of PyTorch, I used CPU for inference. 

To do so, I had to adjust certain parts of the code, first at line 292:

```
 	if torch.cuda.device_count()==0:
		print(f'Running on CPU...')
		args.cuda = False
		ckpt = torch.load(args.model_path,map_location=torch.device('cpu'))
	else:
		print(f'Running on GPU with CUDA as {args.cuda}...')
		ckpt = torch.load(args.model_path)
```
to:
```

	if not args.cuda or torch.cuda.device_count()==0:
		print(f'Running on CPU...')
		args.cuda = False
		ckpt = torch.load(args.model_path,map_location=torch.device('cpu'))
	else:
		print(f'Running on GPU with CUDA as {args.cuda}...')
		ckpt = torch.load(args.model_path)
```
and line 42:

```
	tensor_img = torch.from_numpy(scale_img.astype(np.float32)[:, :, :]).permute(2, 0, 1).cuda()
```
to
```
	tensor_img = torch.from_numpy(scale_img.astype(np.float32)[:, :, :]).permute(2, 0, 1)
	if args.cuda:
		tensor_img = tensor_img.cuda()
```
Removing the --cuda parameter in `scripts/test_samples.sh` then allowed to run inference on CPU. 

The results I'm obtaining are the same as in issue #7.

![1](https://user-images.githubusercontent.com/16069844/137504225-a9a5a13f-1f6d-4a28-82ca-d2b14f3daf00.jpg)
![1](https://user-images.githubusercontent.com/16069844/137504178-b7473472-60f4-4019-8531-98a60c5a37a6.png)

![2](https://user-images.githubusercontent.com/16069844/137504228-11a382d5-6709-4a18-8505-c156a5cd23de.jpg)
![2](https://user-images.githubusercontent.com/16069844/137504186-e671148b-4977-44f2-9ad7-f2271456523c.png)

![3](https://user-images.githubusercontent.com/16069844/137504238-e22756c4-03e7-44cc-b70a-8ed23fdde1dc.jpg)
![3](https://user-images.githubusercontent.com/16069844/137504189-9083ae0d-693d-4325-aea8-4af0fa6e0611.png)

I also ran inference similarly on the AIM-500 dataset, and I obtained the following results in `logs/test_logs/DEBUG.log`:

> INFO:root:Testing numbers: 500
> INFO:root:SAD: 70.16285879981845
> INFO:root:MSE: 0.033924558738880374
> INFO:root:MAD: 0.041689636977158
> INFO:root:SAD TRIMAP: 48.64482158505621
> INFO:root:MSE TRIMAP: 0.09556289661012443
> INFO:root:MAD TRIMAP: 0.13346166896791076
> INFO:root:SAD FG: 17.866437117307104
> INFO:root:SAD BG: 3.651600097455164
> INFO:root:CONN: 67.30147147906628
> INFO:root:GRAD: 58.72859108352662

The artifacts that are obtained are really surprising, and they seem to be induced at a quite low resolution. 

Hope this helps, and we can find a way to have this great repository to work!

**Comment by 99991** [comment]
I also got some artifacts and downgrading skimage did not help. Instead, I removed the line `from skimage.transform import resize` from [`AIM/core/test.py`](https://github.com/JizhiziLi/AIM/blob/7c545c5f5992ba865d679df124d5eb8c37e9ce5e/core/test.py#L17) and added the following function to replace it:

```python
def resize(image, shape):
    if image.dtype == np.uint8:
        image = image / 255.0

    return cv2.resize(image, (shape[1], shape[0]), interpolation=cv2.INTER_NEAREST)
```

The network seems to be extremely sensitive to the resizing function. For example, changing `/ 255.0` to `/ 256.0` messes up the result completely.

The following results have been computed with `torch==1.10.1+cu113` and skimage uninstalled. Using torch 1.7.1 instead makes no difference.

![1](https://user-images.githubusercontent.com/18725165/150329930-f23e77e7-afa2-479c-a01e-2c219c8f82ca.png)
![2](https://user-images.githubusercontent.com/18725165/150329936-501a173a-892e-426e-8e8b-d55432d3d496.png)
![3](https://user-images.githubusercontent.com/18725165/150329938-1dfd72fc-566b-4e2b-af00-658bbdc65bf1.png)

**Comment by watertianyi** [comment]
I also tested and the result is different from yours：
![1](https://github.com/JizhiziLi/AIM/assets/29244715/6f6f3cdf-6a72-4c9f-972f-ab81ce469be4)
![2](https://github.com/JizhiziLi/AIM/assets/29244715/81c4dc9d-1563-4c20-83ad-a4fb9c1580f2)
![3](https://github.com/JizhiziLi/AIM/assets/29244715/c9a7f2a4-3e63-46e6-9ddc-eec38c9bfadd)
