### ISSUE TITLE
Training code

### ISSUE THREAD

**Issue by Kakoedlinnoeslovo** [JizhiziLi/AIM#11]
**Hi, Jizhizi Li 🤗 🤗 🤗.** 
Many thanks for this amazing repo! Works very nice for my images with clothes! 🥳 👌👋

But it seems to me that the results can be further improved by additional training on individual cases. 👀 

Some results:
![image](https://i.ibb.co/QFPkrnC/48cca424-dbcf-4f44-9ee5-9251beed481b-69e12fb1e8103e2830d5f6a21551512b.png)
![image](https://i.ibb.co/w4zh7Nx/f-IA3-N4-AFpl55z-Czq-XCKQ.png)
![image](https://i.ibb.co/FbS6wYp/david-dvoracek-12-P0-rz-SNp-M-unsplash.png)

Do you have some plans for realization the training code? 
I have already seen the previous question on this topic, but I can't wait. 😈 😈 😈 
Thank you for the answer! Have a very very nice day 🤓😄😄

**Comment by JizhiziLi** [comment]
Hi there, 

Thanks for showing interest in our project, we have just released the training code and the code for data processing, welcome to have a try on your own dataset. :)
