### ISSUE TITLE
Number of iterations for each epochs

### ISSUE THREAD

**Issue by anilsathyan7** [JizhiziLi/AIM#16]
How many iterations does it do on each epochs? Form line: https://github.com/JizhiziLi/AIM/blob/master/core/train.py#L81, it looks like it does only 4 iterations for each epochs. Does this approach train the model with all images in one epoch?

**Comment by JizhiziLi** [comment]
Hi there, sorry the 4 iteration was only used while training debug, It was uploaded there by mistake. Thanks for pointing it out, I have already deleted it. And for each epoch, we finish all the iterations.
