### ISSUE TITLE
When do you plan to release the training code?

### ISSUE THREAD

**Issue by syfbme** [JizhiziLi/AIM#2]
Amazing work.

**Comment by JizhiziLi** [comment]
Hi, thanks for the interest, we plan to release the training code along with the models after the IJCAI conference, before the end of the coming August. Please stay tuned to the Github page for further updates.

**Comment by syfbme** [comment]
> Hi, thanks for the interest, we plan to release the training code along with the models after the IJCAI conference, before the end of the coming August. Please stay tuned to the Github page for further updates.

Looking forward to the training code~
