### ISSUE TITLE
Question about the results for DIM+Trimap

### ISSUE THREAD

**Issue by XavierCHEN34** [JizhiziLi/AIM#5]
I've test my trimap based model on AIM-500. However, the results are much better that reported in your paper.  It is reasonable that trimap-based models have advantages over trimap-free ones. 
I wonder that if you did not fuse the foreground and background labels provided by the trimap during test.

**Comment by JizhiziLi** [comment]
Hi there,

Thanks for showing interest in our work. Please note that this work is focused on trimap-free matting methods. Thus, for fair comparison, we trained and tested the trimap-based methods with our unified semantic representation (unimap/duomap/trimap), which may cause a gap with the conventional implementations using the traditional trimaps. I will upload the trimaps used as the inputs for trimap-based methods on AIM-500 soon, where you can have a try with. Thanks!

Cheers,
Jizhizi Li
